### ISSUE TITLE
Raw Files

### ISSUE THREAD

**Issue by mclarenf1lm15** [JBShady/COD5-Remastered#7]
Not really an issue, but would we be able to get the raw files for the most recent update (as of 9/10/24)?

Thanks for the awesome mod!

**Comment by JBShady** [comment]
No. Just kidding, yes, I always upload the code eventually, just takes some time for me to finalize everything before I want to post it & also need to document each change. If you're wanting to modify my mod, just keep a notes file with stuff you're currently changed if you want to remember when you re-download the source.
